Hoaian\WebBundle\Entity\Album:
    type: entity
    table: album
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: user_id
        date:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        comment:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
                default: ''
    lifecycleCallbacks: {  }
