Hoaian\WebBundle\Entity\Cforum:
    type: entity
    table: cforum
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
                default: Chatbox
        level:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        levelDel:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '99'
            column: level_del
    lifecycleCallbacks: {  }
