Hoaian\WebBundle\Entity\District:
    type: entity
    table: district
    indexes:
        provinceid:
            columns:
                - provinceid
    id:
        districtid:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        location:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        provinceid:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
    lifecycleCallbacks: {  }
