Hoaian\WebBundle\Entity\Province:
    type: entity
    table: province
    id:
        provinceid:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
    lifecycleCallbacks: {  }
