Hoaian\WebBundle\Entity\Ward:
    type: entity
    table: ward
    indexes:
        districtid:
            columns:
                - districtid
    id:
        wardid:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        location:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        districtid:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
    lifecycleCallbacks: {  }
